import {publishedJson} from './data-client.mjs';
import {STRATEGIES,validCompetitionSnapshot} from './crypto-strategies-core.mjs';
import {PLATFORMS,assessReadiness,executionProfile,fundingHurdle} from './execution-readiness.mjs';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let data;
try{document.documentElement.dataset.theme=localStorage.getItem('mm-theme-v6')||localStorage.getItem('mm-theme-v5')||'light';}catch{}
$('theme').onclick=()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('mm-theme-v6',theme);}catch{}};
$('strategy').innerHTML=STRATEGIES.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');
$('platforms').innerHTML=PLATFORMS.map(p=>`<article><span class="pill">${esc(p.state)}</span><h3>${esc(p.name)}</h3><p>${esc(p.detail)}</p><p>${esc(p.fees)}</p><a href="${p.url}" target="_blank" rel="noopener">Eligibility source</a> · <a href="${p.feeUrl}" target="_blank" rel="noopener">Fee source</a></article>`).join('');
// Only public setup choices, never credentials or private account responses.
const savedFields=['strategy','budget','order-size','cost-capital','entry-fee','exit-fee','slippage','funding','withdrawal'];
try{const saved=JSON.parse(sessionStorage.getItem('mm-readiness-inputs')||'{}');for(const id of savedFields)if(typeof saved[id]==='string'&&(id!=='strategy'||STRATEGIES.some(s=>s.id===saved[id])))$(id).value=saved[id];}catch{}
for(const id of savedFields)$(id).addEventListener('input',()=>{try{sessionStorage.setItem('mm-readiness-inputs',JSON.stringify(Object.fromEntries(savedFields.map(key=>[key,$(key).value]))));document.body.dataset.updateBlocked='false';}catch{document.body.dataset.updateBlocked='true';}});
function render(){const a=data?.accounts?.[$('strategy').value],r=assessReadiness(a);$('evidence').innerHTML=`<p><strong>${r.eligible?'Research screens passed; private account checks remain':'Keep testing in paper'}</strong></p><p class="muted">${a?`${r.trades} closed trades in the benchmark period. ${r.days.toFixed(1)} forward days.`:'This strategy is waiting for its first published cycle.'}</p>`;$('gates').innerHTML=r.gates.map(g=>`<li class="${g.pass?'pass':''}">${esc(g.label)}</li>`).join('');}
$('strategy').onchange=render;
$('export').onclick=()=>{try{const profile=executionProfile($('strategy').value,{budget:Number($('budget').value),maxOrder:Number($('order-size').value)}),url=URL.createObjectURL(new Blob([JSON.stringify(profile,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='moffitt-execution-preview.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('export-status').textContent='Downloaded in preview mode. No real orders were enabled.';}catch(e){$('export-status').textContent=e.message;}};
function costs(){try{const r=fundingHurdle({capital:Number($('cost-capital').value),entryRate:Number($('entry-fee').value)/100,exitRate:Number($('exit-fee').value)/100,slippageRate:Number($('slippage').value)/100,fundingCost:Number($('funding').value),withdrawalCost:Number($('withdrawal').value)});$('cost-result').textContent=`${(100*r).toFixed(2)}% price rise to cover these costs`;}catch(e){$('cost-result').textContent=e.message;}}
for(const id of ['cost-capital','entry-fee','exit-fee','slippage','funding','withdrawal'])$(id).oninput=costs;costs();render();
async function load(){try{data=await publishedJson('data/crypto-strategies.json',validCompetitionSnapshot);$('notice').textContent=`Paper-only setup. Last strategy receipt: ${new Date(data.generatedAt*1000).toLocaleString()}. No private account is connected to this page.`;render();}catch(e){$('notice').textContent='Strategy evidence unavailable. Setup export remains disarmed; no readiness is inferred.';}}
load();setInterval(()=>{if(document.visibilityState==='visible')load();},60000);
